import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import Navigation from '#/navgation'
import favicon from './favicon.ico'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto flex flex-col min-h-screen">
          <header className="bg-gray-800 text-white p-4 ">
            <div className="flex flex-auto gap-2">
              <Image src={favicon} alt="방울뱀" width={32} />
              <h1 className="text-2xl font-bold">방울뱀</h1>
            </div>
            <Navigation />
          </header>
          <main className="flex-grow bg-gray-100 p-4 text-sm">{children}</main>
          <footer className="bg-gray-800 text-white p-4 flex gap-2 justify-center">
            By <a href="https://github.com/acandiatale">acandiatale</a>
            &#124;<a href="https://github.com/znuzu">znuzu</a>
            &#124;<a href="https://github.com/leejy222">leejy222</a>
          </footer>
        </div>
      </body>
    </html>
  )
}
